### PR TITLE
Pub: 11.19,12.14,13.10,14.7, and more. [release]

### PR DESCRIPTION
**Pull request by mkusaka**
exec `./shared/release.sh 11.19 12.14 13.10 14.7 15.2`
https://www.postgresql.org/about/news/postgresql-152-147-1310-1214-and-1119-released-2592/

### CODE REVIEW

**Comment by JalexChen** [comment]
hi @mkusaka - thanks for putting in the contribution. we are going to have a couple PRs that need to be merged in before we get to this. additionally, it might need a rebase as well. stay tuned!

**Comment by JalexChen** [comment]
hi @mkusaka - the revert was made and we will hold off on some other changes. could you please rebase on main and i'll run the build?

**Comment by mkusaka** [comment]
@JalexChen Oh, thanks! The rebase of this PR has been done :)

**Comment by JalexChen** [comment]
> @JalexChen Oh, thanks! The rebase of this PR has been done :)

hey @mkusaka - just checked the PR. because of the revert, you'll need to generate the dockerfiles (and perhaps rebase) as well. sorry about that. a couple of the versions like 11.9, 12.14, 13.10 etc were affected

**Comment by mkusaka** [comment]
@JalexChen 
Oops sorry. I now understand what I should have done.
I did the following steps to re-generate.

First, on the latest main branch, I made the following changes to `. /shared/release.sh` 

```diff
diff --git a/release.sh b/release.sh
index 2af53c5..f4da361 100755
--- a/release.sh
+++ b/release.sh
@@ -48,13 +48,13 @@ fi
 
 defaultBranch=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
 
-if [[ -n $(git ls-remote --exit-code --heads origin "$branchName")]]; then
- echo "Branch already exists. Please check the branch or PR"
- exit 1
-else
- git checkout -b "${branchName}" "${defaultBranch}"
+# if [[ -n $(git ls-remote --exit-code --heads origin "$branchName")]; then
+# echo "Branch already exists. Please check the branch or PR"
+# exit 1
+# else
+# git checkout -b "${branchName}" "${defaultBranch}"
        shared/gen-dockerfiles.sh "$@"
        git add .
        git commit -m "${commitMSG}"
- git push -u origin "${branchName}"
-fi
+# git push -u origin "${branchName}"
+# fi
```

Next, exec `./shared/release.sh 11.19 12.14 13.10 14.7 15.2` 

Then, force pushed changes to this branch.

Thanks :)

**Comment by JalexChen** [comment]
> @JalexChen Oops sorry. I now understand what I should have done. I did the following steps to re-generate.
> 
> First, on the latest main branch, I made the following changes to `. /shared/release.sh`
> 
> ```diff
> diff --git a/release.sh b/release.sh
> index 2af53c5..f4da361 100755
> --- a/release.sh
> +++ b/release.sh
> @@ -48,13 +48,13 @@ fi
>  
>  defaultBranch=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
>  
> -if [[ -n $(git ls-remote --exit-code --heads origin "$branchName")]]; then
> - echo "Branch already exists. Please check the branch or PR"
> - exit 1
> -else
> - git checkout -b "${branchName}" "${defaultBranch}"
> +# if [[ -n $(git ls-remote --exit-code --heads origin "$branchName")]; then
> +# echo "Branch already exists. Please check the branch or PR"
> +# exit 1
> +# else
> +# git checkout -b "${branchName}" "${defaultBranch}"
>         shared/gen-dockerfiles.sh "$@"
>         git add .
>         git commit -m "${commitMSG}"
> - git push -u origin "${branchName}"
> -fi
> +# git push -u origin "${branchName}"
> +# fi
> ```
> 
> Next, exec `./shared/release.sh 11.19 12.14 13.10 14.7 15.2`
> 
> Then, force pushed changes to this branch.
> 
> Thanks :)

hi yes - with regards to this, the idea was that we would be trying to automate the updates to our images. we were getting unclear errors initially so those added lines were included to curb that. i can see how running `./shared/release.sh` would break if running it twice.

the rationale behind it was that if the release script was run once, the branch would already be there, and any updates to dockerfile generation would be run with `./shared/gen-dockerfiles.sh`, then rebased and pushed. 

i'm pretty sure i can either change those lines or make it more clear in documentation. thank you for pointing it out and also for submitting the PR :)

running the build now.

**Review by JalexChen — APPROVED** [review]

**Pull request merged**
