### PR TITLE
Pre-tune PostgreSQL for CircleCI & test with 15.2 [release]

### PR DESCRIPTION
**Pull request by felicianotech**
This PR attempts to pre-tune PostgreSQL. Part of the point of this is to help solve problems like #47 since we can't dynamically change my PG settings.

This PR also builds the new PG v15.2 image as a way to test these changes.

Whether this is merged or not, we need to build v15.2 and other new releases though if we merge this, those releases should come after.

Also, if this works, we should determine how far back to make the change. The requester in #47 seems to be using 11.x so not recent.

### CODE REVIEW

**Comment by BytesGuy** [comment]
@felicianotech Looks good to me on principle. Do we have any benchmarks on this? Perhaps `pgbench` to see how much this improves the performance whilst testing stability?

**Review by BytesGuy — APPROVED** [review]

**Comment by felicianotech** [comment]
@BytesGuy No benchmarks. How do you use `pgbench` with this image to do so? I determined the changed defaults based on prior knowledge, some reading, and playing with `pgtune`.

**Comment by BytesGuy** [comment]
@felicianotech This is what I used to test if ram disks would make any performance difference. Off the top of my head this will create a database and populate it, then simulator a load of clients running multiple queries

```
      - run: pgbench -i -s 100 -h 127.0.0.1 -p 5432 -d $TEST_DATABASE_URL --quiet
      - run: pgbench -c 100 -T 300 -S -n -p 5432 -d $TEST_DATABASE_URL >> benchmark 2>&1
      - run: tail -n 50 benchmark
```

**Comment by JalexChen** [comment]
i think the changes themselves are fine, but i'm not sure what the benchmarking would be used for specifically in this case; are we looking for any specific increases in performance with `pgbench` and `pgtune` or is this more for addressing how to configure in #47?

**Comment by JalexChen** [comment]
after investigating this issue further: 

- should we follow through with the revert in #71? this change is not deterministic, but there aren't many changes being made to that file. the most important one is actually the addition of `listen_addresses = '*'` for testing purposes.

- technically, the dockerfile has a backwards compatibility symlink, so it could use either the upstream entrypoint or the one that is copied over within this repo. if we do not revert, i would still need to add the old docker-entrypoint.sh back in so older dockerfile versions can still build, but this would be backwards compatible

- i think having the addition of the separate postgres.conf makes sense since it allows users to customize their configuration, especially for settings that can only be set at a certain time. this would also allow us to set the `listen_addresses = '*'` configuration within this file instead of in the entrypoint, which facilitates pulling from upstream

- specifying a postgres.conf is compatible and is [documented](https://github.com/CircleCI-Public/cimg-postgres/pull/71) as one of the ways to do it, so i think this would work for old and new releases without needing to know exactly how far back to go

**Comment by BytesGuy** [comment]
@JalexChen 

* Yes, let's revert this for now until we have a better solution
* As above, let's revert for now to keep things simple
* This is a good idea, we can keep custom configuration separate this way
* We will definitely want to ensure this is well documented from our side too

**Comment by JalexChen** [comment]
Closes #47

**Comment by BytesGuy** [comment]
@JalexChen This looks good to merge 👍

**Comment by dheerajck** [comment]
Can we add these parameters to postgres config
https://discuss.circleci.com/t/can-postgres-config-postgresql-conf-file-be-changed-using-circle-yml/10621/4

fsync=off
synchronous_commit=off
full_page_writes=off
bgwriter_lru_maxpages=0

**Pull request merged**
