### PR TITLE
Added Postgres 11.14 image

### PR DESCRIPTION
**Pull request by schinery**

### CODE REVIEW

**Comment by JalexChen** [comment]
HI @schinery,

Thanks for putting in the time to request this PR. Would you mind editing only the Dockerfile.template and use the gen-dockerfiles script to generate the resulting Dockerfiles and appropriate folders?

**Comment by schinery** [comment]
Hey @JalexChen, these were the steps I used to generate this PR.

1. Ran `./shared/gen-dockerfiles.sh 11.14`
2. Ran `./build-images.sh` which built all the images after amending the output from step 1 (see below)
3. Committed and pushed what was generated

When I ran `./shared/gen-dockerfiles.sh 11.14` it updated `build-images.sh` and `push-images.sh` but removed everything but the `11.14` image from `build-images.sh`, similar to what @blimmer described happened for them in https://github.com/CircleCI-Public/cimg-postgres/pull/42. I reverted these changes with exception of the `11.14` change.

As I've not generated images before I also checked out https://github.com/CircleCI-Public/cimg-postgres/pull/30 to check what I had generated looked similar i.e. Generated images and updated `build-images.sh` and `push-images.sh`.

Given these steps above please could you point out where I've potentially gone wrong so that I can generate the correct image files needed for this PR?

**Comment by JalexChen** [comment]
Hi @schinery,

I apologize for giving you (somewhat) incorrect information. For a PR like yours and blimmer's, where the image version itself (major/minor) per semver tags, doesn't have an existing directory, the ideal situation is to **edit the Dockerfile.template then run ./shared/release.sh** 11.14 (and/or) 12.10. This will run the gen-dockerfiles.sh script and will automatically populate or rewrite several files with the right parameters and inputs, which is the behavior you saw when you ran it yourself, then run build-images.sh and push-images.sh. There is no need to touch or execute any other files (like build-images.sh) when providing an update like this.

The release script will not run on CircleCI without the correct permissions, and we would need to trigger it on our end to finalize, build, and push the new images. 

i've done this update for both of you guys, but I hope you won't be discouraged from continuing to contribute in the future!

The README should also document this as well, if you were curious on next steps in the future. Appreciate you calling attention to this!

**Comment by schinery** [comment]
All good @JalexChen, just got a bit confused my end. Thanks for this explanation, will definitely try again sometime.

Will close this now you've created https://github.com/CircleCI-Public/cimg-postgres/pull/43.

**Pull request closed without merging**
