### PR TITLE
Fix linux group typo

### PR DESCRIPTION
**Pull request by Drowze**
Hello CircleCI crew 👋 

I am using your images and just found this typo. It didn't cause me any problem, just bothered me a bit so I opened this PR 😛

### CODE REVIEW

**Comment by BytesGuy** [comment]
@Drowze Hello! Thanks for this PR. Please can you change this so that only the `Dockerfile.template` file is modified? The individual Dockerfiles are [automatically generated](https://github.com/CircleCI-Public/cimg-postgres#generating-dockerfiles), so we do not want to edit these directly. Thanks!

**Comment by Drowze** [comment]
Got it, updated the pull request 😄

**Comment by BytesGuy** [comment]
Will merge this in once the checks are complete. Thanks @Drowze ! 🎉

**Comment by felicianotech** [comment]
This is one of my favorite kinds of PRs. Thank you.

**Pull request merged**
