### PR TITLE
Pub: 10.21,11.16,12.11,13.7, and more. [release]

### PR DESCRIPTION
**Pull request by schinery**
Regenerating https://github.com/CircleCI-Public/cimg-postgres/pull/48 as I didn't use `./shared/release.sh` previously.

### CODE REVIEW

**Comment by schinery** [comment]
Hey @JalexChen, sorry for tagging you but seeing as you sorted my previous PR out, I thought why not. 

Any chance you could take a look at this one too?

**Comment by JalexChen** [comment]
> Hey @JalexChen, sorry for tagging you but seeing as you sorted my previous PR out, I thought why not.
> 
> Any chance you could take a look at this one too?

Hey @schinery - thanks for being patient here. i'm taking a look now.

**Comment by schinery** [comment]
@JalexChen your commit [here](https://github.com/CircleCI-Public/cimg-postgres/pull/49/commits/65183822fdeab99399e96207b9979b7257a8b4e8), is that something I should of done as part of this PR?

**Comment by JalexChen** [comment]
> 

hey @schinery - i simply just ran gen-dockerfiles script again after changing the base image that postgres builds on to the june version. i didn't spot anything wrong.

**Review by JalexChen — APPROVED** [review]

**Pull request merged**
